public enum DiagnosticCode: String, CaseIterable, Sendable, Hashable {
    case moreHidden = "A001"

    case kdlSyntax = "A101"
    case includeNotFound = "A102"
    case fileUnreadable = "A103"
    case fileTooLarge = "A104"
    case includeEscapes = "A105"
    case includePathForm = "A106"
    case includeCycle = "A107"
    case tooManyFiles = "A108"
    case globEmpty = "A109"
    case includeSyntax = "A110"
    case includePrefix = "A111"
    case packageInclude = "A112"
    case typeAnnotation = "A113"
    case expansionLimit = "A114"
    case stylesheetMissing = "A115"

    case unknownNode = "A201"
    case unknownProperty = "A202"
    case missingArgument = "A203"
    case tooManyArguments = "A204"
    case argumentType = "A205"
    case propertyType = "A206"
    case missingProperty = "A207"
    case noChildren = "A208"
    case wrongPlace = "A209"
    case experimental = "A210"
    case reservedName = "A211"
    case hidesProvider = "A212"
    case luaReserved = "A213"
    case unknownMenuSource = "A214"
    case expressionNotAllowed = "A215"

    case badName = "A301"
    case packageDefineName = "A302"
    case duplicateParameter = "A303"
    case unknownType = "A304"
    case parameterDefault = "A305"
    case unknownDefine = "A306"
    case useCycle = "A307"
    case unknownParameter = "A308"
    case parameterType = "A309"
    case missingParameter = "A310"
    case unknownSlot = "A311"
    case duplicateFill = "A312"
    case dynamicUsePlace = "A313"

    case expressionSyntax = "A401"
    case expressionTooLarge = "A402"
    case unknownRoot = "A403"
    case unknownVar = "A404"
    case unknownField = "A405"
    case filterArguments = "A406"
    case unknownFilter = "A407"
    case filterDefinition = "A408"
    case duplicateFilter = "A409"
    case varSyntax = "A410"
    case derivedPersist = "A411"
    case evaluation = "A412"

    case duplicateDefinition = "A501"
    case overrideWithoutTarget = "A502"
    case disableSyntax = "A503"
    case disableUnknown = "A504"
    case oneMenu = "A505"
    case numericID = "A506"
    case duplicateID = "A507"
    case switchShape = "A508"
    case packageStartsPrograms = "A509"
    case listEntries = "A510"
    case reservedSuffix = "A511"
    case invalidVersion = "A512"
    case versionTooOld = "A513"

    case styleTooLarge = "A601"
    case styleSyntax = "A602"
    case styleNesting = "A603"
    case styleValue = "A604"
    case themeToken = "A605"

    case settingsSyntax = "A701"
    case settingsDuplicate = "A702"
    case settingsValue = "A703"
    case settingsUnknown = "A704"
    case configMissing = "A705"
    case stateSyntax = "A706"
    case stateDuplicate = "A707"
    case stateType = "A708"
    case stateCopy = "A709"
    case legacyImport = "A710"
    case builtinMarketplace = "A711"

    case checkFolder = "A801"
    case checkFixture = "A802"
    case checkUnreadable = "A803"

    public var summary: String {
        switch self {
        case .moreHidden: "More problems of the same kind exist and are not listed."
        case .kdlSyntax: "The file is not valid KDL."
        case .includeNotFound: "An included file does not exist."
        case .fileUnreadable: "A config file exists but cannot be read."
        case .fileTooLarge: "A config file is larger than the size limit."
        case .includeEscapes: "An include path leads outside the config folder."
        case .includePathForm: "An include path must be relative and cannot start with ~."
        case .includeCycle: "Files include each other in a circle."
        case .tooManyFiles: "The config includes more files than allowed."
        case .globEmpty: "A glob pattern matched no files."
        case .includeSyntax: "An include or style node is written wrongly."
        case .includePrefix: "A builtin: or pkg: path lacks the id or the path."
        case .packageInclude: "A package includes a file outside the package."
        case .typeAnnotation: "KDL type annotations are reserved and not allowed."
        case .expansionLimit: "The config grows too large or too deep once includes and uses are expanded."
        case .stylesheetMissing: "A stylesheet file does not exist."
        case .unknownNode: "The node name is not known here."
        case .unknownProperty: "The node has no property with this name."
        case .missingArgument: "A required argument is missing."
        case .tooManyArguments: "The node takes fewer arguments."
        case .argumentType: "An argument has the wrong type."
        case .propertyType: "A property has the wrong type."
        case .missingProperty: "A required property is missing."
        case .noChildren: "The node cannot have children."
        case .wrongPlace: "The node is not allowed at this place."
        case .experimental: "The name is experimental and may change in a later version."
        case .reservedName: "The name is reserved by the language."
        case .hidesProvider: "A name hides a provider with the same name."
        case .luaReserved: "Lua scripting is reserved for a later version."
        case .unknownMenuSource: "The menu source kind is not known."
        case .expressionNotAllowed: "No {…} expression is allowed at this place."
        case .badName: "A define, param, slot, use or fill name is missing or invalid."
        case .packageDefineName: "A define in a package should carry the package id as prefix."
        case .duplicateParameter: "A define declares the same parameter twice."
        case .unknownType: "type= names a type that does not exist."
        case .parameterDefault: "The default of a parameter does not match its type."
        case .unknownDefine: "use names a define that does not exist."
        case .useCycle: "Defines use each other in a circle."
        case .unknownParameter: "use passes a parameter the define does not declare."
        case .parameterType: "use passes a value of the wrong type."
        case .missingParameter: "use does not pass a parameter without default."
        case .unknownSlot: "fill names a slot the define does not have."
        case .duplicateFill: "The same slot is filled twice."
        case .dynamicUsePlace: "A use with an expression as name is not allowed at this place."
        case .expressionSyntax: "An expression inside {…} cannot be read."
        case .expressionTooLarge: "An expression grows too large once its filters are expanded."
        case .unknownRoot: "An expression starts with a name that does not exist here."
        case .unknownVar: "An expression reads a var that is not declared."
        case .unknownField: "A provider has no field with this name."
        case .filterArguments: "A filter gets the wrong number or kind of arguments."
        case .unknownFilter: "The filter name is not known."
        case .filterDefinition: "A filter node is written wrongly."
        case .duplicateFilter: "A filter name is already taken."
        case .varSyntax: "A var node is written wrongly."
        case .derivedPersist: "A derived var cannot be persisted."
        case .evaluation: "An expression failed while the shell was running."
        case .duplicateDefinition: "The same thing is defined twice without override=#true."
        case .overrideWithoutTarget: "override=#true replaces nothing."
        case .disableSyntax: "disable needs surface=, bind= or on=."
        case .disableUnknown: "disable names something that does not exist."
        case .oneMenu: "An element has more than one menu."
        case .numericID: "An id consists only of digits."
        case .duplicateID: "Two elements in a surface have the same id."
        case .switchShape: "A switch contains something other than case and one final default."
        case .packageStartsPrograms: "A package uses an action that starts programs or controls apps."
        case .listEntries: "Children of a list must be - entries."
        case .reservedSuffix: "A name ends with the reserved suffix -error."
        case .invalidVersion: "require names a version that cannot be read."
        case .versionTooOld: "The config needs a newer ApolloShell."
        case .styleTooLarge: "A stylesheet is larger than the size limit and is not used."
        case .styleSyntax: "A stylesheet cannot be read at this place."
        case .styleNesting: "A stylesheet nests deeper than allowed."
        case .styleValue: "A style property has an invalid value."
        case .themeToken: "The theme sets a token the config does not declare."
        case .settingsSyntax: "settings.kdl is not valid KDL."
        case .settingsDuplicate: "settings.kdl sets the same node twice."
        case .settingsValue: "A node in settings.kdl has a value of the wrong type."
        case .settingsUnknown: "settings.kdl contains an unknown node."
        case .configMissing: "settings.kdl names a config that does not exist."
        case .stateSyntax: "A state file cannot be read."
        case .stateDuplicate: "A state file stores the same var twice."
        case .stateType: "A stored value does not match the var's type."
        case .stateCopy: "An unreadable state file could not be set aside."
        case .legacyImport: "Settings from ApolloShell 0.1 could not be imported."
        case .builtinMarketplace: "The built-in Marketplace surfaces did not load."
        case .checkFolder: "apollo check was given a folder it cannot check."
        case .checkFixture: "apollo check was given a fixture that does not exist."
        case .checkUnreadable: "apollo check cannot read a file and uses defaults."
        }
    }
}

extension DiagnosticCode {
    public static var markdown: String {
        var lines = [
            "# Diagnostic codes",
            "",
            "Every problem ApolloShell reports about a config carries a code, such as `error[A201]`. The code stays the same across versions, even when the wording of the message changes.",
            "",
            "| Code | Meaning |",
            "| --- | --- |",
        ]
        for code in allCases {
            lines.append("| `\(code.rawValue)` | \(code.summary) |")
        }
        return lines.joined(separator: "\n") + "\n"
    }
}
