import Foundation

public struct ClipboardList: Equatable, Sendable {
    public struct Entry: Equatable, Sendable {
        public var text: String
        public var date: Date

        public init(text: String, date: Date) {
            self.text = text
            self.date = date
        }
    }

    public static let limit = 20
    public static let maxLength = 10_000

    public static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    public private(set) var entries: [Entry] = []

    public init() {}

    public var items: [String] { entries.map(\.text) }

    public static func records(types: [String]) -> Bool {
        !types.contains(where: skippedTypes.contains)
    }

    public mutating func add(_ text: String, at date: Date = Date()) {
        let clipped = String(text.prefix(Self.maxLength))
        guard !clipped.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        entries.removeAll { $0.text == clipped }
        entries.insert(Entry(text: clipped, date: date), at: 0)
        if entries.count > Self.limit { entries.removeLast(entries.count - Self.limit) }
    }

    public mutating func remove(_ text: String) {
        entries.removeAll { $0.text == text }
    }

    public mutating func clear() {
        entries.removeAll()
    }

    public static func preview(_ text: String) -> String {
        text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
    }
}
