enum ActionsGlobal {
    private typealias S = ProviderSupport

    static let all: [ActionSchema] = [
        ActionSchema(name: "open", arguments: [S.arg("id", .identifier, doc: "Surface id.")], properties: [PropertySchema(name: "screen", type: .string, defaultValue: .null, doc: "Overrides the screen choice.")], doc: "Opens a surface."),
        ActionSchema(name: "close", arguments: [S.arg("id", .identifier, doc: "Surface id.")], properties: [PropertySchema(name: "wait", type: .bool, defaultValue: .bool(false), allowsExpression: false, doc: "Runs the following actions only after closing.")], waits: true, doc: "Closes a surface."),
        ActionSchema(name: "toggle", arguments: [S.arg("id", .identifier, doc: "Surface id.")], doc: "Opens or closes a surface."),
        ActionSchema(name: "close-group", arguments: [S.arg("group", .string, doc: "Group name.")], doc: "Closes all surfaces of a group."),
        ActionSchema(name: "set", arguments: [S.arg("variable", .identifier, doc: "Name of the var."), S.arg("value", .value, required: false, doc: "New value.")], properties: [
            PropertySchema(name: "for", type: .duration, defaultValue: .null, doc: "Set only temporarily."),
            PropertySchema(name: "in", type: .value, defaultValue: .null, doc: "Acts on an entry of a var list."),
            PropertySchema(name: "field", type: .string, defaultValue: .null, allowsExpression: false, doc: "Field of this entry."),
        ], acceptsChildren: true, doc: "Sets the value of a var."),
        ActionSchema(name: "toggle-var", arguments: [S.arg("variable", .identifier, doc: "Name of the var.")], doc: "Inverts a bool value."),
        ActionSchema(name: "reset", arguments: [S.arg("variable", .identifier, doc: "Name of the var.")], doc: "Resets a var to its default value."),
        ActionSchema(name: "list.insert", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "at", type: .number, defaultValue: .null, doc: "Insert position, default at the end."),
            PropertySchema(name: "id-from", type: .string, defaultValue: .null, allowsExpression: false, doc: "Field holding a unique id."),
            PropertySchema(name: "in", type: .value, defaultValue: .null, doc: "Acts on a list in a field of an entry."),
            PropertySchema(name: "field", type: .string, defaultValue: .null, allowsExpression: false, doc: "Field name of this list."),
        ], acceptsChildren: true, doc: "Inserts an entry into a var list."),
        ActionSchema(name: "list.remove", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "at", type: .number, defaultValue: .null, doc: "Position from 0."),
            PropertySchema(name: "key", type: .value, defaultValue: .null, doc: "Key of the entry."),
        ], doc: "Removes an entry from a var list."),
        ActionSchema(name: "list.move", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "from", type: .number, defaultValue: .null, doc: "Source position."),
            PropertySchema(name: "to", type: .number, defaultValue: .null, doc: "Target position."),
            PropertySchema(name: "key", type: .value, defaultValue: .null, doc: "Key instead of from."),
        ], doc: "Moves an entry within a var list."),
        ActionSchema(name: "list.move-to", arguments: [S.arg("from-variable", .identifier, doc: "Source list."), S.arg("to-variable", .identifier, doc: "Target list.")], properties: [
            PropertySchema(name: "from", type: .number, defaultValue: .null, doc: "Source position."),
            PropertySchema(name: "to", type: .number, defaultValue: .null, doc: "Target position."),
        ], doc: "Moves an entry between two var lists."),
        ActionSchema(name: "list.swap", arguments: [S.arg("variable", .identifier, doc: "First var list."), S.arg("index", .number, doc: "Position in the first list, from 0."), S.arg("other-variable", .identifier, doc: "Second var list."), S.arg("other-index", .number, doc: "Position in the second list, from 0.")], doc: "Swaps two entries."),
        ActionSchema(name: "list.update", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "at", type: .number, defaultValue: .null, doc: "Position from 0."),
            PropertySchema(name: "key", type: .value, defaultValue: .null, doc: "Key instead of at."),
        ], acceptsChildren: true, doc: "Merges fields into a record of a var list."),
        ActionSchema(name: "emit", arguments: [S.arg("name", .string, doc: "Event name, sent as user.<name>.")], properties: [
            PropertySchema(name: "event", type: .value, defaultValue: .null, doc: "Record the handlers read as event.<field>."),
        ], doc: "Sends an event to the config's own on handlers, like apollo emit; a chain of emits stops after 16 levels or 256 events."),
        ActionSchema(name: "wait", arguments: [S.arg("duration", .duration, doc: "Wait time, at most 10s.")], waits: true, doc: "Waits before the next action runs."),
        ActionSchema(name: "repeat", arguments: [S.arg("count", .number, doc: "Repetitions, at most 100.")], acceptsChildren: true, doc: "Runs the children several times."),
        ActionSchema(name: "exec", arguments: [ArgumentSchema(name: "command", type: .string, shellQuoted: true, doc: "Command run via /bin/sh -c; each {…} is inserted as one quoted word.")], properties: [PropertySchema(name: "timeout", type: .duration, defaultValue: .string("30s"), allowsExpression: false, doc: "The program is stopped after this time.")], startsProgramsOrControlsApps: true, doc: "Starts any program."),
        ActionSchema(name: "open-url", arguments: [S.arg("url", .string, doc: "Address with a scheme, such as https:// or mailto:.")], startsProgramsOrControlsApps: true, doc: "Opens a URL."),
        ActionSchema(name: "open-file", arguments: [S.arg("path", .path, doc: "File to open, ~ is the home folder.")], properties: [PropertySchema(name: "app", type: .string, defaultValue: .null, doc: "Specific app.")], startsProgramsOrControlsApps: true, doc: "Opens a file."),
        ActionSchema(name: "reveal-file", arguments: [S.arg("path", .path, doc: "File or folder to select in Finder.")], doc: "Reveals a file in Finder."),
        ActionSchema(name: "run-shortcut", arguments: [S.arg("name", .string, doc: "Name of the shortcut.")], startsProgramsOrControlsApps: true, doc: "Runs a shortcut."),
        ActionSchema(name: "clipboard.copy", arguments: [S.arg("text", .string, doc: "Text put on the clipboard as plain text.")], doc: "Copies text to the clipboard."),
        ActionSchema(name: "pick-file", arguments: [S.arg("variable", .identifier, doc: "Target var for the path.")], properties: [
            PropertySchema(name: "folders", type: .bool, defaultValue: .bool(false), allowsExpression: false, doc: "Folders instead of files."),
            PropertySchema(name: "types", type: .list, defaultValue: .null, allowsExpression: false, doc: "Allowed extensions."),
        ], doc: "Opens a file picker."),
        ActionSchema(name: "toast.show", properties: [
            PropertySchema(name: "title", type: .string, defaultValue: .null, doc: "First line, read as toast.title."),
            PropertySchema(name: "body", type: .string, defaultValue: .null, doc: "Text under the title, read as toast.body."),
            PropertySchema(name: "icon", type: .string, defaultValue: .null, doc: "SF Symbol name, read as toast.icon."),
            PropertySchema(name: "kind", type: .string, defaultValue: .null, doc: "Free word the toast can style by, read as toast.kind; default info."),
            PropertySchema(name: "style", type: .string, defaultValue: .string("default"), doc: "Toast style."),
            PropertySchema(name: "duration", type: .duration, defaultValue: .null, doc: "Display duration."),
        ], doc: "Shows a toast."),
        ActionSchema(name: "toast.dismiss", doc: "Closes the clicked toast from inside its content."),
        ActionSchema(name: "osd.show", arguments: [S.arg("id", .identifier, doc: "Id of the osd.")], doc: "Shows an OSD and restarts its timer."),
        ActionSchema(name: "sound", arguments: [S.arg("name", .string, doc: "System sound name.")], doc: "Plays a system sound."),
        ActionSchema(name: "shell.reload-config", doc: "Reloads the config."),
        ActionSchema(name: "shell.restart", doc: "Restarts the process."),
        ActionSchema(name: "shell.quit", doc: "Quits the shell."),
        ActionSchema(name: "config.select", arguments: [S.arg("id", .identifier, doc: "Config id.")], doc: "Switches the config."),
        ActionSchema(name: "theme.select", arguments: [S.arg("id", .identifier, required: false, doc: "Theme id or #null.")], doc: "Switches the theme."),
        ActionSchema(name: "command-center.open", doc: "Opens the command center menu."),
        ActionSchema(name: "marketplace.open", doc: "Opens the Marketplace window."),
        ActionSchema(name: "theme.import", startsProgramsOrControlsApps: false, doc: "Imports a theme file or folder."),
        ActionSchema(name: "theme.open-folder", doc: "Opens the themes folder in Finder."),
        ActionSchema(name: "shell.check-updates", doc: "Checks for updates now."),
        ActionSchema(name: "shell.install-update", doc: "Installs a downloaded update and restarts."),
        ActionSchema(name: "shell.open-config-folder", doc: "Opens the folder of the active config."),
        ActionSchema(name: "shell.edit", arguments: [S.arg("file", .path, doc: "File to open, ~ is the home folder.")], properties: [PropertySchema(name: "line", type: .number, defaultValue: .null, doc: "Line to jump to, from 1.")], startsProgramsOrControlsApps: true, doc: "Opens a file in the editor from settings.kdl."),
        ActionSchema(name: "shell.set-auto-check", arguments: [S.arg("value", .bool, doc: "#true checks for updates once a day.")], doc: "Switches the automatic update check."),
        ActionSchema(name: "shell.set-auto-install", arguments: [S.arg("value", .bool, doc: "#true installs updates when quitting.")], doc: "Switches the automatic update installation."),
        ActionSchema(name: "shell.set-crash-reports", arguments: [S.arg("mode", .enumeration(["ask", "always", "never"]), doc: "ask, always or never.")], doc: "Sets what happens with a crash report."),
        ActionSchema(name: "shell.about", doc: "Shows the About window of ApolloShell."),
        ActionSchema(name: "shell.set-login-item", arguments: [S.arg("value", .bool, doc: "#true starts the shell at login.")], doc: "Adds or removes the shell as a login item."),
    ]
}
