enum ActionsGlobal {
    private typealias S = ProviderSupport

    static let all: [ActionSchema] = [
        ActionSchema(name: "open", arguments: [S.arg("id", .identifier, doc: "Surface id.")], properties: [PropertySchema(name: "screen", type: .string, defaultValue: .null, doc: "Overrides the screen choice.")], doc: "Opens a surface."),
        ActionSchema(name: "close", arguments: [S.arg("id", .identifier, doc: "Surface id.")], properties: [PropertySchema(name: "wait", type: .bool, defaultValue: .bool(false), allowsExpression: false, doc: "Runs the following actions only after closing.")], waits: true, doc: "Closes a surface."),
        ActionSchema(name: "toggle", arguments: [S.arg("id", .identifier, doc: "Surface id.")], doc: "Opens or closes a surface."),
        ActionSchema(name: "close-group", arguments: [S.arg("group", .string, doc: "Group name.")], doc: "Closes all surfaces of a group."),
        ActionSchema(name: "set", arguments: [S.arg("variable", .identifier, doc: "Name of the var."), S.arg("value", .value, required: false, doc: "New value.")], properties: [
            PropertySchema(name: "for", type: .duration, defaultValue: .null, doc: "Set only temporarily."),
            PropertySchema(name: "in", type: .value, defaultValue: .null, doc: "Acts on an entry of a var list."),
            PropertySchema(name: "field", type: .string, defaultValue: .null, allowsExpression: false, doc: "Field of this entry."),
        ], acceptsChildren: true, doc: "Sets the value of a var."),
        ActionSchema(name: "toggle-var", arguments: [S.arg("variable", .identifier, doc: "Name of the var.")], doc: "Inverts a bool value."),
        ActionSchema(name: "reset", arguments: [S.arg("variable", .identifier, doc: "Name of the var.")], doc: "Resets a var to its default value."),
        ActionSchema(name: "list.insert", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "at", type: .number, defaultValue: .null, doc: "Insert position, default at the end."),
            PropertySchema(name: "id-from", type: .string, defaultValue: .null, allowsExpression: false, doc: "Field holding a unique id."),
            PropertySchema(name: "in", type: .value, defaultValue: .null, doc: "Acts on a list in a field of an entry."),
            PropertySchema(name: "field", type: .string, defaultValue: .null, allowsExpression: false, doc: "Field name of this list."),
        ], acceptsChildren: true, doc: "Inserts an entry into a var list."),
        ActionSchema(name: "list.remove", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "at", type: .number, defaultValue: .null, doc: "Position."),
            PropertySchema(name: "key", type: .value, defaultValue: .null, doc: "Key of the entry."),
        ], doc: "Removes an entry from a var list."),
        ActionSchema(name: "list.move", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "from", type: .number, defaultValue: .null, doc: "Source position."),
            PropertySchema(name: "to", type: .number, defaultValue: .null, doc: "Target position."),
            PropertySchema(name: "key", type: .value, defaultValue: .null, doc: "Key instead of from."),
        ], doc: "Moves an entry within a var list."),
        ActionSchema(name: "list.move-to", arguments: [S.arg("fromVariable", .identifier, doc: "Source list."), S.arg("toVariable", .identifier, doc: "Target list.")], properties: [
            PropertySchema(name: "from", type: .number, defaultValue: .null, doc: "Source position."),
            PropertySchema(name: "to", type: .number, defaultValue: .null, doc: "Target position."),
        ], doc: "Moves an entry between two var lists."),
        ActionSchema(name: "list.swap", arguments: [S.arg("variable", .identifier, doc: "First var list."), S.arg("index", .number, doc: "Position."), S.arg("otherVariable", .identifier, doc: "Second var list."), S.arg("otherIndex", .number, doc: "Position.")], doc: "Swaps two entries."),
        ActionSchema(name: "list.update", arguments: [S.arg("variable", .identifier, doc: "Name of the var list.")], properties: [
            PropertySchema(name: "at", type: .number, defaultValue: .null, doc: "Position."),
            PropertySchema(name: "key", type: .value, defaultValue: .null, doc: "Key instead of at."),
        ], acceptsChildren: true, doc: "Merges fields into a record of a var list."),
        ActionSchema(name: "wait", arguments: [S.arg("duration", .duration, doc: "Wait time, at most 10s.")], waits: true, doc: "Waits before the next action runs."),
        ActionSchema(name: "repeat", arguments: [S.arg("count", .number, doc: "Repetitions, at most 100.")], acceptsChildren: true, doc: "Runs the children several times."),
        ActionSchema(name: "exec", arguments: [S.arg("command", .string, doc: "Command run via /bin/sh -c.")], properties: [PropertySchema(name: "timeout", type: .duration, defaultValue: .string("30s"), allowsExpression: false, doc: "Timeout.")], startsProgramsOrControlsApps: true, doc: "Starts any program."),
        ActionSchema(name: "open-app", arguments: [S.arg("bundleID", .string, doc: "Bundle ID.")], startsProgramsOrControlsApps: true, doc: "Launches an app or brings it to the front."),
        ActionSchema(name: "open-url", arguments: [S.arg("url", .string, doc: "URL.")], startsProgramsOrControlsApps: true, doc: "Opens a URL."),
        ActionSchema(name: "open-file", arguments: [S.arg("path", .path, doc: "Path.")], properties: [PropertySchema(name: "app", type: .string, defaultValue: .null, doc: "Specific app.")], startsProgramsOrControlsApps: true, doc: "Opens a file."),
        ActionSchema(name: "reveal-file", arguments: [S.arg("path", .path, doc: "Path.")], doc: "Reveals a file in Finder."),
        ActionSchema(name: "run-shortcut", arguments: [S.arg("name", .string, doc: "Name of the shortcut.")], startsProgramsOrControlsApps: true, doc: "Runs a shortcut."),
        ActionSchema(name: "clipboard.copy", arguments: [S.arg("text", .string, doc: "Text.")], doc: "Copies text to the clipboard."),
        ActionSchema(name: "pick-file", arguments: [S.arg("variable", .identifier, doc: "Target var for the path.")], properties: [
            PropertySchema(name: "folders", type: .bool, defaultValue: .bool(false), allowsExpression: false, doc: "Folders instead of files."),
            PropertySchema(name: "types", type: .list, defaultValue: .null, allowsExpression: false, doc: "Allowed extensions."),
        ], doc: "Opens a file picker."),
        ActionSchema(name: "notify", properties: [
            PropertySchema(name: "title", type: .string, defaultValue: .null, doc: "Title."),
            PropertySchema(name: "body", type: .string, defaultValue: .null, doc: "Text."),
            PropertySchema(name: "icon", type: .string, defaultValue: .null, doc: "Symbol."),
            PropertySchema(name: "kind", type: .string, defaultValue: .null, doc: "Kind."),
            PropertySchema(name: "style", type: .string, defaultValue: .string("default"), doc: "Toast style."),
            PropertySchema(name: "duration", type: .duration, defaultValue: .null, doc: "Display duration."),
        ], doc: "Shows a toast."),
        ActionSchema(name: "toast.dismiss", doc: "Closes the clicked toast from inside its content."),
        ActionSchema(name: "osd.show", arguments: [S.arg("id", .identifier, doc: "Id of the osd.")], doc: "Shows an OSD and restarts its timer."),
        ActionSchema(name: "sound", arguments: [S.arg("name", .string, doc: "System sound name.")], doc: "Plays a system sound."),
        ActionSchema(name: "shell.reload-config", doc: "Reloads the config."),
        ActionSchema(name: "shell.restart", doc: "Restarts the process."),
        ActionSchema(name: "shell.quit", doc: "Quits the shell."),
        ActionSchema(name: "config.select", arguments: [S.arg("id", .identifier, doc: "Config id.")], doc: "Switches the config."),
        ActionSchema(name: "theme.select", arguments: [S.arg("id", .identifier, required: false, doc: "Theme id or #null.")], doc: "Switches the theme."),
        ActionSchema(name: "command-center.open", doc: "Opens the command center menu."),
        ActionSchema(name: "marketplace.open", doc: "Opens the Marketplace window."),
        ActionSchema(name: "theme.import", startsProgramsOrControlsApps: false, doc: "Imports a theme file or folder."),
        ActionSchema(name: "theme.open-folder", doc: "Opens the themes folder in Finder."),
        ActionSchema(name: "shell.check-updates", doc: "Checks for updates now."),
        ActionSchema(name: "shell.install-update", doc: "Installs a downloaded update and restarts."),
        ActionSchema(name: "shell.open-config-folder", doc: "Opens the folder of the active config."),
        ActionSchema(name: "shell.edit", arguments: [S.arg("file", .path, doc: "File.")], properties: [PropertySchema(name: "line", type: .number, defaultValue: .null, doc: "Line.")], startsProgramsOrControlsApps: true, doc: "Opens a file in the editor from settings.kdl."),
        ActionSchema(name: "shell.set-login-item", arguments: [S.arg("value", .bool, doc: "State.")], doc: "Set the login item."),
    ]
}
