enum Filters {
    private static func arg(_ name: String, _ type: ValueType = .any, doc: String) -> ArgumentSchema {
        ArgumentSchema(name: name, type: type, doc: doc)
    }

    private static func optionalArg(_ name: String, _ type: ValueType = .any, doc: String) -> ArgumentSchema {
        ArgumentSchema(name: name, type: type, required: false, doc: doc)
    }

    static let all: [FilterSchema] = [
        FilterSchema(name: "round", arguments: [optionalArg("digits", .number, doc: "Nachkommastellen, Vorgabe 0.")], doc: "rundet eine Zahl."),
        FilterSchema(name: "floor", doc: "rundet ab."),
        FilterSchema(name: "ceil", doc: "rundet auf."),
        FilterSchema(name: "abs", doc: "Betrag einer Zahl."),
        FilterSchema(name: "fixed", arguments: [arg("digits", .number, doc: "genaue Anzahl Nachkommastellen.")], doc: "String mit genau n Nachkommastellen."),
        FilterSchema(name: "clamp", arguments: [arg("low", .number, doc: "untere Grenze."), arg("high", .number, doc: "obere Grenze.")], doc: "begrenzt eine Zahl."),
        FilterSchema(name: "min", arguments: [arg("other", .number, doc: "Vergleichswert.")], doc: "kleinerer Wert."),
        FilterSchema(name: "max", arguments: [arg("other", .number, doc: "Vergleichswert.")], doc: "grösserer Wert."),
        FilterSchema(name: "scale", arguments: [arg("fromLow", .number, doc: "untere Eingangsgrenze."), arg("fromHigh", .number, doc: "obere Eingangsgrenze."), arg("toLow", .number, doc: "untere Ausgangsgrenze."), arg("toHigh", .number, doc: "obere Ausgangsgrenze.")], doc: "bildet einen Bereich linear auf einen anderen ab."),
        FilterSchema(name: "percent", arguments: [optionalArg("digits", .number, doc: "Nachkommastellen, Vorgabe 0.")], doc: "0…1 als Prozent-String."),
        FilterSchema(name: "grouped", arguments: [optionalArg("digits", .number, doc: "Nachkommastellen, Vorgabe 0.")], doc: "Zahl mit Tausendertrennung nach Locale."),
        FilterSchema(name: "bytes", arguments: [optionalArg("unit", .enumeration(["binary", "decimal"]), doc: "Einheitensystem, Vorgabe decimal.")], doc: "Byte-Anzahl lesbar formatiert."),
        FilterSchema(name: "bytes-per-second", arguments: [optionalArg("unit", .enumeration(["binary", "decimal"]), doc: "Einheitensystem, Vorgabe decimal.")], doc: "wie bytes, mit /s."),
        FilterSchema(name: "temperature", doc: "Grad nach der Einheit des Wetter-Providers."),
        FilterSchema(name: "duration", arguments: [optionalArg("style", .enumeration(["short", "clock"]), doc: "Darstellung, Vorgabe clock.")], doc: "Sekunden lesbar formatiert."),
        FilterSchema(name: "date", arguments: [arg("pattern", .string, doc: "ICU-Muster.")], doc: "Datum nach einem Muster formatiert."),
        FilterSchema(name: "relative", doc: "Datum relativ zu jetzt."),
        FilterSchema(name: "string", doc: "wandelt einen Wert in einen String um."),
        FilterSchema(name: "upper", doc: "in Grossbuchstaben."),
        FilterSchema(name: "lower", doc: "in Kleinbuchstaben."),
        FilterSchema(name: "capitalize", doc: "erster Buchstabe grossgeschrieben."),
        FilterSchema(name: "truncate", arguments: [arg("length", .number, doc: "Anzahl Zeichen.")], doc: "schneidet nach n Zeichen mit … ab."),
        FilterSchema(name: "pad", arguments: [arg("length", .number, doc: "Zielbreite."), optionalArg("character", .string, doc: "Füllzeichen, Vorgabe Leerzeichen.")], doc: "füllt links auf."),
        FilterSchema(name: "replace", arguments: [arg("search", .string, doc: "gesuchter Text."), arg("replacement", .string, doc: "Ersatztext.")], doc: "ersetzt einen Teiltext."),
        FilterSchema(name: "split", arguments: [arg("separator", .string, doc: "Trenner.")], doc: "zerlegt einen String in eine Liste."),
        FilterSchema(name: "starts-with", arguments: [arg("prefix", .string, doc: "gesuchtes Präfix.")], doc: "prüft den Anfang eines Strings."),
        FilterSchema(name: "ends-with", arguments: [arg("suffix", .string, doc: "gesuchtes Suffix.")], doc: "prüft das Ende eines Strings."),
        FilterSchema(name: "json", doc: "liest einen String als JSON."),
        FilterSchema(name: "number", doc: "liest einen String als Zahl."),
        FilterSchema(name: "count", doc: "Länge einer Liste, eines Strings oder Records."),
        FilterSchema(name: "first", doc: "erstes Element oder Zeichen."),
        FilterSchema(name: "last", doc: "letztes Element oder Zeichen."),
        FilterSchema(name: "at", arguments: [arg("index", .number, doc: "Stelle.")], doc: "Element an einer Stelle."),
        FilterSchema(name: "take", arguments: [arg("count", .number, doc: "Anzahl.")], doc: "erste n Elemente."),
        FilterSchema(name: "skip", arguments: [arg("count", .number, doc: "Anzahl.")], doc: "überspringt die ersten n Elemente."),
        FilterSchema(name: "slice", arguments: [arg("start", .number, doc: "erste Stelle."), arg("end", .number, doc: "Stelle danach.")], doc: "Ausschnitt einer Liste oder eines Strings."),
        FilterSchema(name: "reverse", doc: "dreht eine Liste oder einen String um."),
        FilterSchema(name: "sort", arguments: [optionalArg("field", .string, doc: "Feld, nach dem sortiert wird."), optionalArg("direction", .enumeration(["desc"]), doc: "absteigend, wenn gesetzt.")], doc: "sortiert eine Liste."),
        FilterSchema(name: "unique", doc: "entfernt Doppelte, erste bleibt."),
        FilterSchema(name: "join", arguments: [arg("separator", .string, doc: "Trenner.")], doc: "verbindet eine Liste zu einem String."),
        FilterSchema(name: "where", arguments: [arg("field", .string, doc: "Feldname."), arg("value", .any, doc: "gesuchter Wert.")], doc: "filtert Records nach Gleichheit eines Felds."),
        FilterSchema(name: "where-not", arguments: [arg("field", .string, doc: "Feldname."), arg("value", .any, doc: "ausgeschlossener Wert.")], doc: "filtert Records nach Ungleichheit eines Felds."),
        FilterSchema(name: "map", arguments: [arg("field", .string, doc: "Feldname.")], doc: "zieht ein Feld aus jedem Record."),
        FilterSchema(name: "contains", arguments: [arg("value", .any, doc: "gesuchter Wert.")], doc: "prüft, ob ein Wert enthalten ist."),
        FilterSchema(name: "index-of", arguments: [arg("value", .any, doc: "gesuchter Wert.")], doc: "Stelle eines Werts oder null."),
        FilterSchema(name: "index-where", arguments: [arg("field", .string, doc: "Feldname."), arg("values", .list, doc: "gesuchte Werte."), optionalArg("order", .enumeration(["last"]), doc: "letzten statt ersten Treffer nehmen.")], doc: "Stelle des ersten oder letzten passenden Records."),
        FilterSchema(name: "fuzzy", arguments: [arg("query", .string, doc: "Suchtext."), optionalArg("field", .string, doc: "Feldname, Vorgabe name.")], doc: "unscharfe Suche über eine Liste."),
        FilterSchema(name: "app-search", arguments: [arg("query", .string, doc: "Suchtext.")], feature: "core", doc: "unscharfe App-Suche mit Nutzungsrang."),
        FilterSchema(name: "month-grid", arguments: [optionalArg("offset", .number, doc: "Monatsversatz."), optionalArg("firstWeekday", .string, doc: "erster Wochentag.")], doc: "Wochen eines Monats als Liste von Listen."),
        FilterSchema(name: "url", doc: "normalisiert eine Adresse oder liefert null."),
        FilterSchema(name: "symbol-exists", doc: "prüft, ob ein SF-Symbol existiert."),
        FilterSchema(name: "chord", doc: "zeigt eine Tastenkombination mit Symbolen an."),
        FilterSchema(name: "hotkey-warning", doc: "Warntext zu einer Tastenkombination oder null."),
        FilterSchema(name: "default", arguments: [arg("fallback", .any, doc: "Ersatzwert für null.")], doc: "wie ??, Ersatz für null."),
        FilterSchema(name: "bool", doc: "Wahrheitswert eines Werts."),
        FilterSchema(name: "keys", doc: "Schlüssel eines Records als Liste."),
        FilterSchema(name: "values", doc: "Werte eines Records als Liste."),
    ]
}
