enum Filters {
    private static func arg(_ name: String, _ type: ValueType = .any, doc: String) -> ArgumentSchema {
        ArgumentSchema(name: name, type: type, doc: doc)
    }

    private static func optionalArg(_ name: String, _ type: ValueType = .any, doc: String) -> ArgumentSchema {
        ArgumentSchema(name: name, type: type, required: false, doc: doc)
    }

    static let all: [FilterSchema] = [
        FilterSchema(name: "round", arguments: [optionalArg("digits", .number, doc: "Decimal places, default 0.")], doc: "Rounds a number."),
        FilterSchema(name: "floor", doc: "Rounds down."),
        FilterSchema(name: "ceil", doc: "Rounds up."),
        FilterSchema(name: "abs", doc: "Absolute value of a number."),
        FilterSchema(name: "fixed", arguments: [arg("digits", .number, doc: "Exact number of decimal places.")], doc: "String with exactly n decimal places."),
        FilterSchema(name: "clamp", arguments: [arg("low", .number, doc: "Lower bound."), arg("high", .number, doc: "Upper bound.")], doc: "Clamps a number."),
        FilterSchema(name: "min", arguments: [arg("other", .number, doc: "Comparison value.")], doc: "Smaller value."),
        FilterSchema(name: "max", arguments: [arg("other", .number, doc: "Comparison value.")], doc: "Larger value."),
        FilterSchema(name: "scale", arguments: [arg("from-low", .number, doc: "Lower input bound."), arg("from-high", .number, doc: "Upper input bound."), arg("to-low", .number, doc: "Lower output bound."), arg("to-high", .number, doc: "Upper output bound.")], doc: "Maps a range linearly onto another."),
        FilterSchema(name: "percent", arguments: [optionalArg("digits", .number, doc: "Decimal places, default 0.")], doc: "0…1 as a percent string."),
        FilterSchema(name: "grouped", arguments: [optionalArg("digits", .number, doc: "Decimal places, default 0.")], doc: "Number with thousands separators per locale."),
        FilterSchema(name: "bytes", arguments: [optionalArg("unit", .enumeration(["binary", "decimal"]), doc: "Unit system, default decimal.")], doc: "Byte count, formatted for reading."),
        FilterSchema(name: "bytes-per-second", arguments: [optionalArg("unit", .enumeration(["binary", "decimal"]), doc: "Unit system, default decimal.")], doc: "Like bytes, with /s."),
        FilterSchema(name: "temperature", doc: "Degrees in the unit of the weather provider."),
        FilterSchema(name: "duration", arguments: [optionalArg("style", .enumeration(["short", "clock"]), doc: "Style, default clock.")], doc: "Seconds, formatted for reading."),
        FilterSchema(name: "date", arguments: [arg("pattern", .string, doc: "ICU pattern."), optionalArg("zone", .string, doc: "Time zone like Europe/Zurich, default the one of the system.")], doc: "Date formatted with a pattern."),
        FilterSchema(name: "relative", doc: "Date relative to now."),
        FilterSchema(name: "string", doc: "Converts a value to a string."),
        FilterSchema(name: "shell-quote", doc: "One shell word in single quotes, safe to insert into a /bin/sh command."),
        FilterSchema(name: "upper", doc: "In uppercase."),
        FilterSchema(name: "lower", doc: "In lowercase."),
        FilterSchema(name: "capitalize", doc: "First letter capitalized."),
        FilterSchema(name: "truncate", arguments: [arg("length", .number, doc: "Number of characters.")], doc: "Truncates after n characters with …."),
        FilterSchema(name: "pad", arguments: [arg("length", .number, doc: "Target width."), optionalArg("character", .string, doc: "Padding character, default space.")], doc: "Pads on the left."),
        FilterSchema(name: "replace", arguments: [arg("search", .string, doc: "Text to find."), arg("replacement", .string, doc: "Text to put in its place.")], doc: "Replaces part of a text."),
        FilterSchema(name: "split", arguments: [arg("separator", .string, doc: "Text between the parts, not kept in the result.")], doc: "Splits a string into a list."),
        FilterSchema(name: "starts-with", arguments: [arg("prefix", .string, doc: "Prefix to find.")], doc: "Checks the start of a string."),
        FilterSchema(name: "ends-with", arguments: [arg("suffix", .string, doc: "Suffix to find.")], doc: "Checks the end of a string."),
        FilterSchema(name: "json", doc: "Parses a string as JSON."),
        FilterSchema(name: "number", doc: "Parses a string as a number."),
        FilterSchema(name: "count", doc: "Length of a list, string or record."),
        FilterSchema(name: "first", doc: "First element or character."),
        FilterSchema(name: "last", doc: "Last element or character."),
        FilterSchema(name: "at", arguments: [arg("index", .number, doc: "Position from 0; negative counts from the end, -1 is the last.")], doc: "Element at a position."),
        FilterSchema(name: "take", arguments: [arg("count", .number, doc: "Number of elements to keep, 0 or more.")], doc: "First n elements."),
        FilterSchema(name: "skip", arguments: [arg("count", .number, doc: "Number of elements to drop, 0 or more.")], doc: "Skips the first n elements."),
        FilterSchema(name: "slice", arguments: [arg("start", .number, doc: "First position."), arg("end", .number, doc: "Position after the end.")], doc: "Slice of a list or string."),
        FilterSchema(name: "reverse", doc: "Reverses a list or string."),
        FilterSchema(name: "sort", arguments: [optionalArg("field", .string, doc: "Field to sort by."), optionalArg("direction", .enumeration(["desc"]), doc: "Descending when set.")], doc: "Sorts a list."),
        FilterSchema(name: "unique", doc: "Removes duplicates, the first one stays."),
        FilterSchema(name: "join", arguments: [arg("separator", .string, doc: "Text put between two elements.")], doc: "Joins a list into a string."),
        FilterSchema(name: "where", arguments: [arg("field", .string, doc: "Field name."), arg("value", .any, doc: "Value to find.")], doc: "Filters records by equality of a field."),
        FilterSchema(name: "where-not", arguments: [arg("field", .string, doc: "Field name."), arg("value", .any, doc: "Excluded value.")], doc: "Filters records by inequality of a field."),
        FilterSchema(name: "map", arguments: [arg("field", .string, doc: "Field name.")], doc: "Takes a field from each record."),
        FilterSchema(name: "contains", arguments: [arg("value", .any, doc: "Value to find.")], doc: "Checks whether a value is contained."),
        FilterSchema(name: "index-of", arguments: [arg("value", .any, doc: "Value to find.")], doc: "Position of a value or null."),
        FilterSchema(name: "index-where", arguments: [arg("field", .string, doc: "Field name."), arg("values", .list, doc: "Values to find."), optionalArg("order", .enumeration(["last"]), doc: "Take the last match instead of the first.")], doc: "Position of the first or last matching record."),
        FilterSchema(name: "fuzzy", arguments: [arg("query", .string, doc: "Search text."), optionalArg("field", .string, doc: "Field name, default name.")], doc: "Fuzzy search over a list."),
        FilterSchema(name: "app-search", arguments: [arg("query", .string, doc: "Search text.")], feature: "core", doc: "Fuzzy app search with usage ranking."),
        FilterSchema(name: "first-free-frame", arguments: [arg("width", .number, doc: "Width of the new frame."), arg("height", .number, doc: "Height of the new frame."), optionalArg("page-width", .number, doc: "Width of the canvas, default 839."), optionalArg("page-height", .number, doc: "Height of the canvas, default 392."), optionalArg("gap", .number, doc: "Minimum distance to the other frames, default 12.")], feature: "canvas-layout", stability: .experimental, doc: "First free place for a frame among a list of records with x, y, width, height: rows from the top, in them from the left, or null when the canvas is full."),
        FilterSchema(name: "sun-moon", arguments: [arg("latitude", .number, doc: "Latitude in degrees."), arg("longitude", .number, doc: "Longitude in degrees.")], feature: "sun-moon", stability: .experimental, doc: "Sun and moon on a date: sunrise, sunset, noon, always-up, always-down, moonrise, moonset (null, not computed), moon-phase 0…1, moon-illumination 0…1, moon-symbol, moon-name."),
        FilterSchema(name: "month-grid", arguments: [optionalArg("offset", .number, doc: "Month offset."), optionalArg("first-weekday", .string, doc: "First day of the week.")], doc: "Weeks of a month as a list of lists."),
        FilterSchema(name: "url", doc: "Normalizes a URL or returns null."),
        FilterSchema(name: "symbol-exists", doc: "Checks whether an SF Symbol exists."),
        FilterSchema(name: "chord", doc: "Shows a key combination with symbols."),
        FilterSchema(name: "hotkey-warning", doc: "Warning text for a key combination or null."),
        FilterSchema(name: "default", arguments: [arg("fallback", .any, doc: "Fallback value for null.")], doc: "Like ??, fallback for null."),
        FilterSchema(name: "bool", doc: "Truth value of a value."),
        FilterSchema(name: "keys", doc: "Keys of a record as a list."),
        FilterSchema(name: "values", doc: "Values of a record as a list."),
    ]
}
