import Foundation
import ApolloConfig

public enum SchemaFormat: Sendable {
    case text, json, markdown
}

public struct SchemaEntry: Sendable {
    public var kind: String
    public var name: String
    public var doc: String
    public var example: String?
    public var arguments: [ArgumentSchema]
    public var properties: [PropertySchema]
    public var fields: [FieldSchema]
    public var members: [String]
    public var stability = "stable"
    public var feature = ""
}

public enum SchemaText {
    public static func entries(_ registry: SchemaRegistry) -> [SchemaEntry] {
        var result: [SchemaEntry] = []
        for node in registry.allNodes {
            result.append(SchemaEntry(kind: "node", name: node.name, doc: node.doc, example: node.example, arguments: node.arguments, properties: node.properties, fields: [], members: node.handlers, stability: node.stability.rawValue, feature: node.feature))
        }
        for action in registry.actions.values {
            result.append(SchemaEntry(kind: "action", name: action.name, doc: action.doc, example: nil, arguments: action.arguments, properties: action.properties, fields: [], members: [], stability: action.stability.rawValue, feature: action.feature))
        }
        for provider in registry.providers.values {
            let members = provider.actions.map(\.name) + provider.events.map(\.name)
            result.append(SchemaEntry(kind: "provider", name: provider.id, doc: provider.doc, example: nil, arguments: [], properties: provider.settings, fields: provider.fields, members: members, stability: provider.stability.rawValue, feature: provider.feature))
        }
        for filter in registry.filters.values {
            result.append(SchemaEntry(kind: "filter", name: filter.name, doc: filter.doc, example: nil, arguments: filter.arguments, properties: [], fields: [], members: [], stability: filter.stability.rawValue, feature: filter.feature))
        }
        for event in registry.events.values {
            result.append(SchemaEntry(kind: "event", name: event.name, doc: event.doc, example: nil, arguments: [], properties: [], fields: event.fields, members: [], feature: event.feature))
        }
        let order = sections.map(\.kind)
        return result.sorted {
            if $0.kind != $1.kind { return order.firstIndex(of: $0.kind)! < order.firstIndex(of: $1.kind)! }
            return $0.name < $1.name
        }
    }

    public static func render(_ registry: SchemaRegistry, name: String?, format: SchemaFormat) -> [String]? {
        let all = entries(registry)
        guard let name else {
            switch format {
            case .text:
                return all.map { "\($0.kind) \($0.name): \($0.doc)" }
            case .json:
                return [JSONText.encode(.list(all.map(json)))]
            case .markdown:
                return [document(all)]
            }
        }
        let matches = all.filter { $0.name == name }
        guard !matches.isEmpty else { return nil }
        switch format {
        case .text:
            return [matches.map(text).joined(separator: "\n\n")]
        case .json:
            return [JSONText.encode(.list(matches.map(json)))]
        case .markdown:
            return [matches.map(markdown).joined(separator: "\n\n")]
        }
    }

    static let sections: [(kind: String, title: String, intro: String)] = [
        ("node", "Nodes", "Blocks, surfaces and the other nodes a config file is made of."),
        ("action", "Actions", "What a handler such as `on-click` can do."),
        ("provider", "Providers", "Live data from the system, read in expressions as `<provider>.<field>`."),
        ("filter", "Filters", "Transformations inside expressions, written `value | filter`."),
        ("event", "Events", "Events that `on \"<event>\"` can react to."),
    ]

    static let preamble = """
        # Configuration reference

        Every node, action, provider, filter and event a config can use. This
        file is generated by `apollo schema --markdown` and the tests compare it
        with that output, so change the registry, not this file. Entries marked
        *experimental* may still change.
        """

    static func document(_ entries: [SchemaEntry]) -> String {
        var parts = [preamble]
        for section in sections {
            let members = entries.filter { $0.kind == section.kind }
            guard !members.isEmpty else { continue }
            parts.append("## \(section.title)\n\n\(section.intro)")
            parts += members.map(markdown)
        }
        return parts.joined(separator: "\n\n")
    }

    static func text(_ entry: SchemaEntry) -> String {
        var lines = ["\(entry.name) (\(entry.kind))", "  \(entry.doc)"]
        for argument in entry.arguments {
            lines.append("  argument \(argument.name): \(typeText(argument.type))\(argument.required ? "" : "?")\(argument.variadic ? "..." : "") - \(argument.doc)")
        }
        for property in entry.properties {
            lines.append("  property \(property.name): \(typeText(property.type))\(property.defaultValue.map { " = " + JSONText.encode($0) } ?? "") - \(property.doc)")
        }
        for field in entry.fields {
            lines.append("  field \(field.path.joined(separator: ".")): \(typeText(field.type))\(field.nullable ? "?" : "") - \(field.doc)")
        }
        if !entry.members.isEmpty {
            lines.append("  also: \(entry.members.joined(separator: ", "))")
        }
        if let example = entry.example, !example.isEmpty {
            lines.append("  example: \(example)")
        }
        return lines.joined(separator: "\n")
    }

    static func cell(_ text: String) -> String {
        text.replacingOccurrences(of: "|", with: "\\|").replacingOccurrences(of: "\n", with: " ")
    }

    static func markdown(_ entry: SchemaEntry) -> String {
        let marker = entry.stability == "stable" ? "" : ", *\(entry.stability)*"
        var lines = ["### `\(entry.name)` (\(entry.kind)\(marker))", "", entry.doc]
        let rows = entry.arguments.map { "| argument | `\($0.name)`\($0.variadic ? "..." : "") | \(cell(typeText($0.type))) | \($0.required ? "required" : "") | \(cell($0.doc)) |" }
            + entry.properties.map { "| property | `\($0.name)` | \(cell(typeText($0.type))) | \(cell(defaultText($0))) | \(cell($0.doc)) |" }
            + entry.fields.map { "| field | `\($0.path.joined(separator: "."))` | \(cell(typeText($0.type) + ($0.nullable ? " or null" : ""))) | | \(cell($0.doc)) |" }
        if !rows.isEmpty {
            lines += ["", "| | Name | Type | Default | |", "| --- | --- | --- | --- | --- |"] + rows
        }
        if !entry.members.isEmpty {
            let label = entry.kind == "provider" ? "Actions and events" : "Handlers"
            lines += ["", "\(label): " + entry.members.map { "`\($0)`" }.joined(separator: ", ")]
        }
        if let example = entry.example, !example.isEmpty {
            lines += ["", "```kdl", example, "```"]
        }
        return lines.joined(separator: "\n")
    }

    static func defaultText(_ property: PropertySchema) -> String {
        if property.required { return "required" }
        guard let value = property.defaultValue else { return "" }
        return "`\(JSONText.encode(value))`"
    }

    static func json(_ entry: SchemaEntry) -> Value {
        var pairs: [(String, Value)] = [
            ("kind", .string(entry.kind)),
            ("name", .string(entry.name)),
            ("doc", .string(entry.doc)),
            ("stability", .string(entry.stability)),
            ("feature", .string(entry.feature)),
        ]
        if let example = entry.example { pairs.append(("example", .string(example))) }
        pairs.append(("arguments", .list(entry.arguments.map { argument in
            .record(Record([("name", .string(argument.name)), ("type", .string(typeText(argument.type))), ("required", .bool(argument.required)), ("variadic", .bool(argument.variadic)), ("doc", .string(argument.doc))]))
        })))
        pairs.append(("properties", .list(entry.properties.map { property in
            .record(Record([("name", .string(property.name)), ("type", .string(typeText(property.type))), ("default", property.defaultValue ?? .null), ("stability", .string(property.stability.rawValue)), ("doc", .string(property.doc))]))
        })))
        pairs.append(("fields", .list(entry.fields.map { field in
            .record(Record([("path", .string(field.path.joined(separator: "."))), ("type", .string(typeText(field.type))), ("nullable", .bool(field.nullable)), ("doc", .string(field.doc))]))
        })))
        pairs.append(("members", .list(entry.members.map(Value.string))))
        return .record(Record(pairs))
    }

    static func typeText(_ type: ValueType) -> String {
        switch type {
        case .any: "any"
        case .string: "string"
        case .number: "number"
        case .bool: "bool"
        case .duration: "duration"
        case .keyChord: "key-chord"
        case .path: "path"
        case .identifier: "identifier"
        case .value: "value"
        case .actions: "actions"
        case .list: "list"
        case .record: "record"
        case .enumeration(let names): names.map { "\"\($0)\"" }.joined(separator: "|")
        case .oneOf(let types): types.map(typeText).joined(separator: "|")
        }
    }
}
